import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Card from '../components/card'

import { Service as ApiService } from '../services'

export default function Home({pictures}) {
  const { data: photos } = pictures || { data: [] }

  return (
    <div className={styles.container}>
      <Head>
        <title>Mars Rover Photos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1>
          Welcome to <a href="https://nextjs.org">NASA PICS!</a>
        </h1>
        <input type="text" name="Searc" value="" placeholder="Search Image"/>
      </header>

      <main className={styles.main}>
        <div className={styles.picturesContainer}>
          {
            photos && photos.map(pic => <Card key={pic.id} picture={pic}/>)
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Jonatan Waibsnaider
        </a>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const params = { sol:1000, page:1 }

  try {
    const pictures = await new ApiService(params).getPictures()

    return { props: { pictures } }
  } catch (error) {
    return { notFound: true }
  }

};
